### ISSUE TITLE
error on jwtDecode(token)

### ISSUE THREAD

**Issue by Kachulio1** [microsoftgraph/microsoft-graph-explorer-v2#103]
<img width="1680" alt="Screen Shot 2019-07-11 at 23 58 48" src="https://user-images.githubusercontent.com/22243090/61085001-e2fe8b80-a437-11e9-9ca8-3c24c839737d.png">

the error is caused by this [line](https://github.com/microsoftgraph/microsoft-graph-explorer-v2/blob/5b8df51b3187ec9a4c9e6eef6082379afcacb295/src/app/services/graph-client/HelloAuthProvider.ts#L92)

there are issues opened https://github.com/auth0/jwt-decode/issues/61 https://github.com/auth0/jwt-decode/issues/76
but no fix.

**Comment by cwahome** [comment]
This was fixed by #265 . Decoding the access token to get the scopes is no longer a requirement.
