### ISSUE TITLE
Accessibility Issue #1: Keyboard Navigation - users must be able to navigate to all interactive interface components using a keyboard.

### ISSUE THREAD

**Issue by bettirosengugi** [microsoftgraph/microsoft-graph-explorer-v2#116]
![image](https://user-images.githubusercontent.com/4668452/61375161-d7331f00-a8a6-11e9-917b-d5e0d4732971.png)

**Comment by cwahome** [comment]
Once in a tablist control, to move from one tab to another, you need to use arrow keys.
