### ISSUE TITLE
Accessibility Issue #11: Keyboard interaction - A custom widget must support the keyboard interaction specified by its design pattern

### ISSUE THREAD

**Issue by bettirosengugi** [microsoftgraph/microsoft-graph-explorer-v2#126]
![image](https://user-images.githubusercontent.com/4668452/61376125-33973e00-a8a9-11e9-8356-b61df2eb64af.png)

**Comment by cwahome** [comment]
Monaco alert is controlled as an external dependency. I do not currently have access to it
