### ISSUE TITLE
Code Component

### ISSUE THREAD

**Issue by darrelmiller** [microsoftgraph/microsoft-graph-explorer-v2#13]

**Comment by bettirosengugi** [comment]
The goal for this task is to integrate code snippets API to Graph Explorer. 

Right @darrelmiller ?

**Comment by darrelmiller** [comment]
Yes.  But more specifically using the React/Redux terminology, this is the React UI component that will render the code snippet tab, the language selector and the content of the code snippet.  It would also be valuable to have a "copy" button to simplify copying the code into the clipboard.
