### ISSUE TITLE
add a Share Link button on Graph Explorer V2

### ISSUE THREAD

**Issue by bettirosengugi** [microsoftgraph/microsoft-graph-explorer-v2#143]
Add this button on the screenshot below
![image](https://user-images.githubusercontent.com/4668452/64519611-1d33be80-d2fd-11e9-8e7e-eb0e277c2a0f.png)

To allow users share the query string on their session as it is by copying it. 

![image](https://user-images.githubusercontent.com/4668452/64519674-418f9b00-d2fd-11e9-8052-3c8eead064bd.png)

Additional requirements.
1. **Enable backward compatibility to enable share links between Classic and V2**
2. **Enable sharing the request body as well is the user has input a key and a value as part of the request body**

**Comment by jthake-msft** [comment]
Can we ensure that the new share capability not onyl allows to share GETs but also those with a Request Body. As a feature enhancement, probably tracked as separate work item...
