### ISSUE TITLE
Add permissions tab to Graph Explorer V2

### ISSUE THREAD

**Issue by bettirosengugi** [microsoftgraph/microsoft-graph-explorer-v2#155]
The current Graph Explorer V2, doesn't have Permissions yet. We shall integrate to Permissions API when it's ready. This will make it easy for users to make queries without needing to know which permissions they need since the GE API's Permission endpoint will handle all that. GE being a learning tool, it will be wise to add a tab next to request header tab names permissions. This tab will check the query ran, and inform the user the permissions they need for that query so that they can reuse this information in their applications.

The permissions tab should be added next to the Request Header tab like the arrow below shows: 

![image](https://user-images.githubusercontent.com/4668452/64871567-2a7ae100-d64e-11e9-85c8-fa59e42c8e4d.png)

**Comment by darrelmiller** [comment]
This should not be necessary.

**Comment by bettirosengugi** [comment]
We have gotten headway with the Permissions endpoint and therefore we are going to close this issue and wait to integrate to Permissions endpoint on Graph Explorer API

**Comment by bettirosengugi** [comment]
Reopened the issue after discussing with @darrelmiller  on a better way to show the permissions tab.

**Comment by cwahome** [comment]
@darrelmiller and @bettirosengugi if we handle it this way, we would negate the work done to fix #106 

> Users making GET requests do not use the Request Component. Not rendering the Request Component gives us more screen real estate to show responses.

**Questions**
Would we be in use of the permissions tab in all requests? 
Would we also be performing any actions on the permissions?
