### ISSUE TITLE
Fix responsiveness issues in GE V2

### ISSUE THREAD

**Issue by bettirosengugi** [microsoftgraph/microsoft-graph-explorer-v2#158]
Repro Steps: 
1. Go to http://graphtryit-staging.azurewebsites.net/ on Chrome
2. Right click the page and select inspect
3. Select Toggle Device Toolbar
4. Switch between screen sizes. the UI is distorted. Below is a screenshot.

![image](https://user-images.githubusercontent.com/4668452/64415991-03953b80-d09f-11e9-8668-722baa585ee9.png)

I scrolled the same page and took the below screenshot
![image](https://user-images.githubusercontent.com/4668452/64416028-11e35780-d09f-11e9-874e-462eb4d820d7.png)

**Comment by cwahome** [comment]
@bettirosengugi kindly present the screen size used in this particular example
