### ISSUE TITLE
Add Terms of use information bar to Graph Explorer V2

### ISSUE THREAD

**Issue by bettirosengugi** [microsoftgraph/microsoft-graph-explorer-v2#168]
**Is your feature request related to a problem? Please describe.**
There's need to notify users that by using GE they have agreed to Microsoft's terms of use and add links that they can access to go through them.

**Describe the solution you'd like**
See below screenshot
![image](https://user-images.githubusercontent.com/4668452/64519930-c4185a80-d2fd-11e9-88c8-db0c568b5250.png)

**Describe alternatives you've considered**
The terms of use can fall right below the query bar but this is subject to discussion.

**Additional context**
N/A

**Comment by cwahome** [comment]
@bettirosengugi, might you have a list of other apps that have that informational bar that we can use for reference? I'd appreciate other options other than the one stated because of crowding the view.

**Comment by Kachulio1** [comment]
@cwahome @bettirosengugi  what if we have it at the top of the page like this.
<img width="1680" alt="Screen Shot 2019-09-09 at 15 10 26" src="https://user-images.githubusercontent.com/22243090/64530154-20d33f80-d315-11e9-92f1-208116a3f96a.png">
see the Get the Bing + MSN extension
