### ISSUE TITLE
Reload samples from a cache as opposed to loading from server 

### ISSUE THREAD

**Issue by bettirosengugi** [microsoftgraph/microsoft-graph-explorer-v2#170]
**Describe the bug**
The samples load from the server every time, it's better to load them from a cache after fetching them the first time

**To Reproduce**
1. Go to http://graphtryit-staging.azurewebsites.net/
2. Change tabs from Samples to History
3. Change back to Samples
4. You'll see the progress bar loading samples again. 

**Expected behavior**
The loading shouldn't happen at all since the data will be on the cache already, and there should be no delay showing the samples.

**Screenshots**
![image](https://user-images.githubusercontent.com/4668452/64533262-c4275300-d31b-11e9-8acf-7fcf104a6978.png)

**Desktop (please complete the following information):**
 - OS: [Windows 10]
 - Browser [e.g. chrome]
 - Version N/A

**Smartphone (please complete the following information):**

**Additional context**

**Comment by jobala** [comment]
What do you think of having the loading samples text below the spinner? @bettirosengugi  @cwahome
