### ISSUE TITLE
Update Graph Explorer Run Query to request scope from PermissionsAPI

### ISSUE THREAD

**Issue by darrelmiller** [microsoftgraph/microsoft-graph-explorer-v2#172]
In order to obtain a valid token to make the call to Microsoft Graph it is necessary for us to pass in the required scopes when making the request.

Flow:

1) User clicks Run Query
2) Call Permissions API with method and URL.  Array of scopes is returned, ordered from least permissive to most.
3) Take first scope, add to auth middleware options, pass via Javascript SDK request.
4) If consent required, MSAL will display consent dialog.  Once done, call should continue.
5) if response is 403, take next scope and repeat step 3

I have asked Muthu for an example of how to create the auth middleware options and pass to SDK.  We will probably need to to use Popup consent instead of redirect to maintain request state.

**Comment by jobala** [comment]
FYI, we are using hellojs and not MSAL.

**Comment by darrelmiller** [comment]
@jobala Do you know if it is possible with hello.js to update the desired scopes on every request but only get a consent dialog if previously unconsented scopes are requested.

**Comment by jobala** [comment]
@darrelmiller in theory this is possible.

We can get a new access-token scope-wise, if a scope has not been consented to then the consent screen will be shown.

**Comment by darrelmiller** [comment]
@jobala I was chatting with Jeremy and we were wondering why not just move back to the Graph Javascript SDK and MSAL?  We won't be attempting to enable sign-in in TryIt until MSAL supports iFrames and we are now deploying V2 as a component, so MSAL should work fine in V2.

**Comment by jobala** [comment]
@darrelmiller yes I agree. Implementing msal should be about 2 days worth of work as the lessons learnt in implementing it in ge-classic are transferrable. @bettirosengugi do you want me to work on this before I go OOF or after I am back?
