### ISSUE TITLE
Bug: Fix the never ending loading progress bar in V2 -tst environment

### ISSUE THREAD

**Issue by bettirosengugi** [microsoftgraph/microsoft-graph-explorer-v2#178]
**Describe the bug**
There's a never ending loading progress bar on the V2 -tst environment' s page. It appears at the bottom of the page, in a distorted way,

**To Reproduce**
1. Go to https://developer.microsoft-tst.com/en-us/graph/graph-explorer-v2/preview?1&setvar=routegraph:https://nghia4:20444
2. Let the page load
3. Scroll down the page
4. You'll see the loading progress bar

**Expected behavior**
The loading progress bar should disappear as soon as the contents load.

**Screenshots**
![image](https://user-images.githubusercontent.com/4668452/64773084-6af93280-d55a-11e9-8606-6a54c0f12928.png)

**Desktop (please complete the following information):**
 - OS: [Windows]
 - Browser [Chrome and Edge]
 - Version []

**Additional context**

**Comment by cwahome** [comment]
Have you had a chance to talk to the portal team? this could either be a shared responsibility or a purely portal issue.
