### ISSUE TITLE
Setup CI/CD for GE V2 to the try it site and the V2 preview site

### ISSUE THREAD

**Issue by bettirosengugi** [microsoftgraph/microsoft-graph-explorer-v2#181]
**Is your feature request related to a problem? Please describe.**
We have the following links to host Graph Explorer Try it and Graph Explorer Preview
http://graphtryit.azurewebsites.net
http://graphtryit-staging.azurewebsites.net
https://developer.microsoft-tst.com/en-us/graph/graph-explorer-v2/preview
https://developer.microsoft-int.com/en-us/graph/graph-explorer-v2/preview
https://developer.microsoft.com/en-us/graph/graph-explorer-v2/preview

At the moment, the deployment from GitHub is semi-manual and we would want to have a way to automatically deploy from GitHub branches.

**Describe the solution you'd like**
Automatic deployment to both sites (Try it and Preview) when changes are approved.

We can use the branching strategy suggested by @MIchaelMainer here: https://teams.microsoft.com/l/message/19:a710d75161804aecaf3ef3bc3239b1e6@thread.skype/1567548067131?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=1fc2aa55-29ee-4d2e-90cc-4b2ffa6c4f7e&parentMessageId=1567548067131&teamName=Graph%20Client%20Tooling&channelName=Graph%20Explorer&createdTime=1567548067131

**Describe alternatives you've considered**

**Additional context**

**Comment by MIchaelMainer** [comment]
I sent out a link to a document for comment and discussion around the branching strategy. @jobala @cwahome let's close on our approach for branching, merging, and deployment to server branches.
