### ISSUE TITLE
Add a run button on the Code Snippets tab to allow users to run the code and get results.

### ISSUE THREAD

**Issue by bettirosengugi** [microsoftgraph/microsoft-graph-explorer-v2#192]
**Is your feature request related to a problem? Please describe.**
It would be nice to have users run the code under the code snippets tab and see what the code returns.

**Describe the solution you'd like**
Integrate to the Playground tool that @jobala  and @andrueastman worked on during FHL 2019 and add a button on the code snippets tab that when clicked runs the code and return the results to the user still on the same tab.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by jobala** [comment]
Closing this based on the discussion we had over the developer sync.

The consensus was that this feature is not worth the trouble plus customers can use the samples starter kits.
