### ISSUE TITLE
UpdateUrl Action

### ISSUE THREAD

**Issue by darrelmiller** [microsoftgraph/microsoft-graph-explorer-v2#21]

**Comment by Kachulio1** [comment]
I have noticed that issues don't have descriptions and it's hard to know what to do if you are not part of the core team. 😄

**Comment by Kachulio1** [comment]
But I guess going forward the will have

**Comment by darrelmiller** [comment]
@Kachulio1 You raise a good point.  These issues have been more like placeholders for us to prioritize tasks.  Moving forward we should make an effort for these tasks to be more descriptive so as to enable contribution.

**Comment by bettirosengugi** [comment]
This  task was completed.
