### ISSUE TITLE
UI changes for V2

### ISSUE THREAD

**Issue by bettirosengugi** [microsoftgraph/microsoft-graph-explorer-v2#218]
**Is your feature request related to a problem? Please describe.**

1. The link icons next to samples are too close to the scrollbar on the right.
![image](https://user-images.githubusercontent.com/4668452/66809557-3fd97880-ef36-11e9-9554-58a514f1867f.png)
2. Use a darker color for the sidebar component to create a contrast with docs since this is a tool. Suggestion is to use the background color in the sidebar component for this page: https://outlook.office365.com
![image](https://user-images.githubusercontent.com/4668452/66809989-0ead7800-ef37-11e9-9b3d-2b9d3fc9eff0.png)
3. Show status  for the http code returned on success and on fail  as well with the right background color and the right **Icon** as in the screenshots below: 
![image](https://user-images.githubusercontent.com/4668452/66810187-65b34d00-ef37-11e9-85de-1942cb086e2c.png)
![image](https://user-images.githubusercontent.com/4668452/66810212-7237a580-ef37-11e9-9153-eae318375959.png)
4.  Add a tile for the request options with  the right background color according to REST API color code, as the screenshot below: 
![image](https://user-images.githubusercontent.com/4668452/66810468-01dd5400-ef38-11e9-8161-0167ed25ca48.png)
![image](https://user-images.githubusercontent.com/4668452/66810541-20dbe600-ef38-11e9-8765-0e0f424b40d4.png)
5. Use 3 dots icon for the drop down in History tab instead of the arrow down.
![image](https://user-images.githubusercontent.com/4668452/66810744-8334e680-ef38-11e9-87d0-d3315ac5b89d.png)
6. Add background color on the Request Options tab next to the Query tab like in the screenshot below: 

![image](https://user-images.githubusercontent.com/4668452/66810873-c8591880-ef38-11e9-9eb0-88ba69c4319e.png)

**Comment by cwahome** [comment]
@bettirosengugi  cc @jobala 
Moved this to separate issues:

* #225
* #226 
* #227 
* #228 
* #229 
* #230
