### ISSUE TITLE
Sign In button still showing after Signing In

### ISSUE THREAD

**Issue by jobala** [microsoftgraph/microsoft-graph-explorer-v2#260]
**Describe the bug**
After a user has logged through a pop up, the sign-in button is still displayed as the application is fetching user data.

**To Reproduce**
1. Click on Sign In
2. Sign In through the pop up
3. See that it takes a while before signed in user information is displayed.

**Expected behavior**
I expected that a spinner or something that indicates there a network request in progress to be shown.

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: [Windows]
 - Browser [Chrome]
 - Version [78.0.3904.70]

**Additional context**
N/A

**Comment by bettirosengugi** [comment]
The solution to this is adding a spinner
