### ISSUE TITLE
As a User, I want a quick hyperlink to launch jwt.ms

### ISSUE THREAD

**Issue by jthake-msft** [microsoftgraph/microsoft-graph-explorer-v2#279]
On the Authorization tab, where the copy button is, we should promote the https://jwt.ms 

People are not aware of this.

It would be GREAT if we could pass the token through as a query string to svae copy and pasting, but I don't believe it supports it.

**Comment by jobala** [comment]
The msal team doesn't want us encouraging users to split the token open, therefore closing this.
