### ISSUE TITLE
Fix Localization issues

### ISSUE THREAD

**Issue by bettirosengugi** [microsoftgraph/microsoft-graph-explorer-v2#342]
**Describe the bug**
The portal is not localized, so when you got to Fr-fr for instance, the page is not translated to French

**To Reproduce**
1. Go to to https://developer.microsoft.com/fr-FR/graph/graph-explorer/preview
2. The page loads in English

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/4668452/72712859-fd4eba00-3b7c-11ea-98e4-7c822350aeb4.png)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by jobala** [comment]
Fixed in #341
