### ISSUE TITLE
add code format standard by adding Prettier Configuration

### ISSUE THREAD

**Issue by Kachulio1** [microsoftgraph/microsoft-graph-explorer-v2#39]
[Prettier Recommended Configuration](https://github.com/prettier/eslint-plugin-prettier)

**Comment by jobala** [comment]
@Kachulio1 do you have the bandwidth to work on this?

**Comment by Kachulio1** [comment]
Yeah, I could work on it.
Or do you have a high priority task?

**Comment by jobala** [comment]
Would you like a more high priority task?

**Comment by Kachulio1** [comment]
Yes

**Comment by jobala** [comment]
Alright, you can work on adding Prettier while we figure that out.
