### ISSUE TITLE
Sample Request History

### ISSUE THREAD

**Issue by jobala** [microsoftgraph/microsoft-graph-explorer-v2#45]
Store requests made in IndexedDb.

**Comment by jobala** [comment]
@Kachulio1 do you have the bandwidth to pick this up?

**Comment by Kachulio1** [comment]
Yeah sure.
Question, all requests or are there specific ones?

**Comment by jobala** [comment]
All requests.

You should also save the request's headers & responses if they have any

**Comment by Kachulio1** [comment]
Ok, I was on holiday haven't worked on this yet.

**Comment by jobala** [comment]
@Kachulio1 are you still working on this? Adding @thewahome to this conversation.

**Comment by Kachulio1** [comment]
@jobala Yeah, I will, I've been super busy in the past few weeks.

**Comment by Kachulio1** [comment]
what's the timeframe?

**Comment by jobala** [comment]
No pressure, I was just following up. Let us know when you start working on this.

**Comment by Kachulio1** [comment]
👍

**Comment by Kachulio1** [comment]
Question is it ok if I use this https://github.com/jakearchibald/idb
a Polyfill for IndexedDB, so that we can use Promises which is better than using IndexedDB Events and it's open source.

**Comment by Kachulio1** [comment]
@jobala ☝️and how should we do the cache invalidation?

**Comment by jobala** [comment]
@Kachulio1 it is fine to use the polyfill for IndexedDb.

What is the context for cache invalidation?

**Comment by Kachulio1** [comment]
Oh, I mean how long should the data in indexedDB be valid for.

**Comment by jobala** [comment]
Forever, until the user deletes the data.

**Comment by bettirosengugi** [comment]
@cwahome worked on this and the PR has been approved and merged.
